on:
  pull_request:
    branches:
      - master
jobs:
  foo:
    name: static check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@sarif
        with:
          version: "2021.1.2"
